# fly.toml app configuration file generated for upsell-technical on 2024-12-16T07:26:15-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'upsell-technical'
primary_region = 'scl'

[env]
  PORT = '3000'
  HOST = 'https://upsell-technical.fly.dev'
  SHOPIFY_API_KEY = '264af22d5700c32542bd100c347ca7b9'
  SCOPES = 'write_products, read_products'


[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
