# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f8187422ed491da8eeba4e9343042303"
application_url = "https://bands-sick-price-bio.trycloudflare.com"
embedded = true
name = "chekout-upsell"
handle = "chekout-upsell"

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://bands-sick-price-bio.trycloudflare.com/auth/callback",
  "https://bands-sick-price-bio.trycloudflare.com/auth/shopify/callback",
  "https://bands-sick-price-bio.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "technical-assessment.myshopify.com"
automatically_update_urls_on_dev = true
